feat: profile page basic markup and styles
UkrainianItFamily/hrtools-frontend pull request #3
Opened 2022-07-08 15:18 UTC by Roman-Kasko-UITF

2022-07-08 20:37 UTC, AntonTitovUITF requested changes

2022-07-08 20:37 UTC, AntonTitovUITF commented on src/pages/user-profile/user-profile.jsx
> +            <svg height="16" viewBox="0 0 48 48" width="16" xmlns="http://www.w3.org/2000/svg">
You can move all svg to assets/images.

2022-07-09 18:28 UTC, Roman-Kasko-UITF commented on src/app.jsx
> +import { UserProfile } from 'src/pages/index';
+

2022-07-09 18:32 UTC, Roman-Kasko-UITF commented on src/pages/index.js
> +import UserProfile from 'src/pages/user-profile/user-profile';
+

2022-07-09 18:32 UTC, Roman-Kasko-UITF commented on src/pages/user-profile/user-profile.jsx
> +import userPhoto from '../../assets/images/user-photo.jpg';
+

2022-07-09 18:32 UTC, Roman-Kasko-UITF commented on src/pages/user-profile/user-profile.jsx
> +import * as Profile from './style';
+

2022-07-09 18:35 UTC, Roman-Kasko-UITF commented on src/pages/user-profile/style.js
> +import styled from '@emotion/styled';
+

2022-07-09 18:44 UTC, Roman-Kasko-UITF commented on src/pages/user-profile/user-profile.jsx
> +        <Profile.MainNavigation>
+

2022-07-22 09:10 UTC, merged